# Generate a new config when a config map is not defined.
# kubevirt-ansible: "yedit" from lib_utils (openshift-ansible) is not present, so rewritten

- name: Set web console config properties from inventory variables
  block:
    - name: Change consoleBaseAddress
      lineinfile:
        path: "{{ mktemp.stdout }}/{{ __console_config_file }}"
        regexp: "^  consoleBaseAddress:.*$"
        line: "  consoleBaseAddress: 'https://{{ kubevirt_web_ui_hostname }}'"
    - name: Change consoleBasePath
      lineinfile:
        path: "{{ mktemp.stdout }}/{{ __console_config_file }}"
        regexp: "^  consoleBasePath:.*$"
        line: "  consoleBasePath: '{{ kubevirt_web_ui_base_path | default('') }}'"
    - name: Change masterPublicURL
      lineinfile:
        path: "{{ mktemp.stdout }}/{{ __console_config_file }}"
        regexp: "^  masterPublicURL:.*$"
        line: "  masterPublicURL: '{{ openshift_master_public_api_url }}'"
    - name: Change oauthEndpointCAFile
      lineinfile:
        path: "{{ mktemp.stdout }}/{{ __console_config_file }}"
        regexp: "^  oauthEndpointCAFile:.*$"
        line: "  oauthEndpointCAFile: '{{ kubevirt_web_ui_auth_ca_file }}'"
    - name: Change logoutRedirect
      lineinfile:
        path: "{{ mktemp.stdout }}/{{ __console_config_file }}"
        regexp: "^  logoutRedirect:.*$"
        line: "  logoutRedirect: '{{ openshift_master_logout_url | default('') }}'"
    - name: Change documentationBaseURL
      lineinfile:
        path: "{{ mktemp.stdout }}/{{ __console_config_file }}"
        regexp: "^  documentationBaseURL:.*$"
        line: "  documentationBaseURL: '{{ kubevirt_web_ui_documentation_base_url }}'"
# Context selector is temporarily removed - https://github.com/kubevirt/web-ui/issues/67
#    - name: Add context selector URL
      # Add the developer console URL to the console picker on upgrade
#      lineinfile:
#        path: "{{ mktemp.stdout }}/{{ __console_config_file }}"
#        regexp: "^  developerConsolePublicURL:.*$"
#        line: "  developerConsolePublicURL: '{{ console_picker_developer_console_public_url | default('') }}'"
#    - name: Copy for debug
#      shell: >
#        cp "{{ mktemp.stdout }}/{{ __console_config_file }}" "/tmp/__console_config_file"

