---
- hosts: masters[0]
  connection: local
  gather_facts: False
  vars:
    network_role: network-multus
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  roles:
    - { role: "network-multus", when: network_role == 'network-multus'}

- hosts: masters[0]
  connection: local
  gather_facts: False
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  roles:
    - role: kubevirt

- hosts: masters[0]
  connection: local
  environment:
    http_proxy: ""
  roles:
    - role: "cdi"

- import_playbook: kubevirt-web-ui/config.yml

