---
- name: Console Install Checkpoint Start
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Console install 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_console:
          title: "Console Install"
          playbook: "playbooks/kubevirt-web-ui/config.yml"
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- name: Console 
  # hosts: oo_first_master
  hosts: masters[0]
  vars:
    first_master: "{{ masters[0] }}"
    # first_master: "{{ oo_first_master }}"
  tasks:
  - import_role:
      name: kubevirt_web_ui

- name: Console Install Checkpoint End
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Console install 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_console:
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
